replicaCount: 2

image:
  repository: image-uploader   #Docker image name
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  host: image-uploader.local

serviceAccount:
  create: true
  name: image-uploader-sa

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
