apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uploader-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: uploader.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uploader-image-uploader
            port:
              number: 5000
